// Generated by .NET Reflector from D:\working\temp\2\Managed\Assembly-CSharp.dll
using ICSharpCode.SharpZipLib.BZip2;
using System;
using System.IO;
using System.Runtime.InteropServices;
using System.Security.Cryptography;
using System.Text;

public class MdcStr
{
    protected const int WRITE_BUFFER_SIZE = 0x4000;

    public static string Dc(string str, uint eorData = 0, uint? crc = new uint?())
    {
        byte[] buffer5;
        byte[] buffer = Convert.FromBase64String(str);
        if (crc.HasValue && (Crc32.Compute(buffer) != crc.Value))
        {
            throw new IOException("MdcStr:Dc Crc Error");
        }
        if (eorData != 0)
        {
            byte[] buffer2 = new byte[] { (byte)eorData, (byte)(eorData >> 8), (byte)(eorData >> 0x10), (byte)(eorData >> 0x18) };
            int length = buffer.Length;
            for (int i = 0; i < length; i++)
            {
                buffer[i] = (byte)(buffer[i] ^ buffer2[i % 4]);
            }
        }
        //byte[] bytes = Encoding.UTF8.GetBytes(NetworkManager.GetMk());
        //byte[] rgbIV = Encoding.UTF8.GetBytes(NetworkManager.GetCv());
        byte[] bytes = Encoding.UTF8.GetBytes("z5pHloeLgfxfM98bdfpLdf7r");
        byte[] rgbIV = Encoding.UTF8.GetBytes("JdKxEnse");
        TripleDESCryptoServiceProvider provider = new TripleDESCryptoServiceProvider();
        using (MemoryStream stream = new MemoryStream())
        {
            using (CryptoStream stream2 = new CryptoStream(stream, provider.CreateDecryptor(bytes, rgbIV), CryptoStreamMode.Write))
            {
                stream2.Write(buffer, 0, buffer.Length);
                stream2.Close();
            }
            buffer5 = stream.ToArray();
            stream.Close();
        }
        using (MemoryStream stream3 = new MemoryStream())
        {
            using (MemoryStream stream4 = new MemoryStream(buffer5))
            {
                using (BZip2InputStream stream5 = new BZip2InputStream(stream4))
                {
                    int num4;
                    byte[] buffer6 = new byte[0x4000];
                    while ((num4 = stream5.Read(buffer6, 0, buffer6.Length)) > 0)
                    {
                        stream3.Write(buffer6, 0, num4);
                    }
                    stream5.Close();
                }
                stream4.Close();
            }
            buffer5 = stream3.ToArray();
            stream3.Close();
        }
        return Encoding.UTF8.GetString(buffer5);
    }
}
